ver.1 Создал ветку и добавил в неё пустой файл(Вавилов)
alexander-sidorov/m-pt1-58-22 pull request #10
Opened 2022-11-25 18:57 UTC by EvgVavilov

2022-11-30 12:19 UTC, alexander-sidorov requested changes

2022-11-30 12:19 UTC, alexander-sidorov commented on hw/eugene_vavilov/__init__.py
> +1
Женя, сделай плз этот файл полностью пустым, без ничего

2022-11-30 16:08 UTC, alexander-sidorov submitted a review, later dismissed

2022-12-01 00:41 UTC, alexander-sidorov requested changes

2022-12-01 00:41 UTC, alexander-sidorov commented on hw/eugene_vavilov/__init__.py
> +
Сделай плз все `__init__.py` настолько же пустыми, насколько и `lecture.py`: в нём вообще ничего нет, а в `__init__.py` есть пустая строка

2022-12-01 19:43 UTC, EvgVavilov commented
Проверьте коммит lesson 4 add v1.1 . В "Black" код отформатировал. На что ошибка не могу понять.

2022-12-01 19:49 UTC, EvgVavilov commented
В lecture_test я неправильно импортировал Decimal?

2022-12-02 13:04 UTC, alexander-sidorov requested changes

2022-12-02 13:04 UTC, alexander-sidorov commented on hw/eugene_vavilov/lesson04/lecture.py
> +    summa = float((Decimal(rubles) + (Decimal(coins) / 100)) * Decimal(amount))
По условию задачи функция должна возвращать Decimal

2022-12-02 13:04 UTC, alexander-sidorov commented on hw/eugene_vavilov/lesson04/lecture.py
> +        isinstance(number, int | float | Decimal) != 1
Немного не так. 

Предикаты не надо сравнивать с 1,0,True,False, они уже сами bool возвращают.

isinstance - предикат.

второе: тип нужно проверить только для complex, раз уж так) для остальных хватит и сравнений на > / < / ==

2022-12-02 13:04 UTC, alexander-sidorov commented on hw/eugene_vavilov/lesson04/lecture.py
> +        or number == complex
Вот это условие никогда не будет True

2022-12-02 13:04 UTC, alexander-sidorov commented on hw/eugene_vavilov/lesson04/lecture.py
> +                assert 0, "Ошибка"
Никакая это не ошибка, если 0 )

2022-12-08 20:32 UTC, alexander-sidorov requested changes

2022-12-08 20:32 UTC, alexander-sidorov commented on hw/eugene_vavilov/lesson04/lecture_test.py
> +assert task_01_money(1, 2, 3) == Decimal("3.06")
эти проверки нужно перенести в тестовую функцию (`def test_...`), функцию создать

2022-12-10 13:14 UTC, alexander-sidorov approved these changes

2022-12-10 13:15 UTC, merged