mikita_karmanaw_lesson12
alexander-sidorov/m-pt1-58-22 pull request #106
Opened 2022-12-23 17:49 UTC by karmaxa

2022-12-25 13:06 UTC, alexander-sidorov requested changes

2022-12-25 13:06 UTC, alexander-sidorov commented on data.json
> +{"name": "Dim"}
`git rm -f data.json`

2022-12-25 13:06 UTC, alexander-sidorov commented on hw/mikita_karmanaw/lesson12/lesson.py
> +            else:
```python
else:
    pass
```

можно вообще никогда не писать

2022-12-25 13:06 UTC, alexander-sidorov commented on hw/mikita_karmanaw/lesson12/lesson.py
> +            self.headers.update({header[0]: header[1]})
неоптимально

2022-12-25 13:16 UTC, karmaxa commented on hw/mikita_karmanaw/lesson12/lesson.py
> +            self.headers.update({header[0]: header[1]})
это про метод update?

2022-12-26 18:03 UTC, alexander-sidorov commented on hw/mikita_karmanaw/lesson12/lesson.py
> +            self.headers.update({header[0]: header[1]})
да

2022-12-26 18:05 UTC, alexander-sidorov requested changes
и ещё пр назван не по тз

2022-12-27 20:25 UTC, alexander-sidorov requested changes

2022-12-27 20:25 UTC, alexander-sidorov commented on data.json
> +{"name": "Dim"}
дубль два) этот файл коммитить не надо!

2022-12-27 20:25 UTC, alexander-sidorov commented on hw/mikita_karmanaw/lesson12/lesson.py
> +        self.method, self.path, self.http_version = head[0], head[1], head[2]
```python
self.method, self.path, self.http_version = head
```

2022-12-27 20:55 UTC, karmaxa commented on hw/mikita_karmanaw/lesson12/lesson.py
> +        self.method, self.path, self.http_version = head[0], head[1], head[2]
done

2022-12-28 06:21 UTC, alexander-sidorov approved these changes

2022-12-28 06:21 UTC, merged