Eugene vavilov lesson 12
alexander-sidorov/m-pt1-58-22 pull request #118
Opened 2022-12-25 11:59 UTC by EvgVavilov

2022-12-26 18:02 UTC, alexander-sidorov requested changes

2022-12-26 18:02 UTC, alexander-sidorov commented on hw/eugene_vavilov/lesson12/lesson.py
> +            try:  # noqa SIM105
поиск по `SIM105` даёт это: https://github.com/MartinThoma/flake8-simplify/issues/5

2022-12-26 18:02 UTC, alexander-sidorov commented on hw/eugene_vavilov/lesson12/lesson.py
> +            self.headers.update({_[0]: _[1]})
ТЗ

2022-12-26 18:02 UTC, alexander-sidorov commented on hw/eugene_vavilov/lesson12/lesson.py
> +        body_end = response.find("}")
а зачем? если респонс будет в формате текста? хтмл? хмл? бейс64?

2022-12-26 18:02 UTC, alexander-sidorov commented on hw/eugene_vavilov/lesson12/lesson_test.py
> +    Accept: */*
теперь понятно, запрос в неправильном формате

2022-12-27 08:10 UTC, EvgVavilov commented on hw/eugene_vavilov/lesson12/lesson.py
> +        url = urlparse(url)
Здесь сойдёмся на минус бал))

2022-12-27 08:20 UTC, EvgVavilov commented on hw/eugene_vavilov/lesson12/lesson.py
> +        request = request.strip()
Исправил

2022-12-27 08:21 UTC, EvgVavilov commented on hw/eugene_vavilov/lesson12/lesson.py
> +        methed_end = request.find(" ")
Исправил

2022-12-27 08:21 UTC, EvgVavilov commented on hw/eugene_vavilov/lesson12/lesson.py
> +            try:  # noqa SIM105
Исправил

2022-12-27 08:21 UTC, EvgVavilov commented on hw/eugene_vavilov/lesson12/lesson.py
> +        for _ in headers_list:
Исправил

2022-12-27 08:22 UTC, EvgVavilov commented on hw/eugene_vavilov/lesson12/lesson.py
> +            self.headers.update({_[0]: _[1]})
Я не понял в чём несоответствие, объясните пожалуйста

2022-12-27 08:25 UTC, EvgVavilov commented on hw/eugene_vavilov/lesson12/lesson.py
> +        body_end = response.find("}")
Вы имеете ввиду поиск последнего элемента body через фигурную скобку?

2022-12-27 08:27 UTC, EvgVavilov commented on hw/eugene_vavilov/lesson12/lesson_test.py
> +    Accept: */*
Я запрос исправил, если не правильно понял то поправьте меня

2022-12-27 20:18 UTC, alexander-sidorov commented on hw/eugene_vavilov/lesson12/lesson.py
> +            self.headers.update({_[0]: _[1]})
разница в том, что для обновления одного ключа надо... обновлять один ключ)

а не создавать целый отдельный словарь, а потом заставлять `dict.update()` запускать итератор по всему этому словарю, чтобы в итоге ... обновить один ключ

<img width="738" alt="image" src="https://user-images.githubusercontent.com/76160017/209718099-e8b68fd4-b5e7-4021-88d0-68c69b16be96.png">

2022-12-27 20:19 UTC, alexander-sidorov commented on hw/eugene_vavilov/lesson12/lesson.py
> +        body_end = response.find("}")
да: body может быть абсолютно любым, поэтому пытаюсь понять, зачем там искать скобку

2022-12-27 20:20 UTC, alexander-sidorov commented on hw/eugene_vavilov/lesson12/lesson.py
> +        url = urlparse(url)
:D времени ещё 17 дней! точно согласен на -1 ?

2022-12-27 20:22 UTC, alexander-sidorov requested changes

2022-12-27 20:22 UTC, alexander-sidorov commented on hw/eugene_vavilov/lesson12/lesson.py
> +            self.headers.update({i[0]: i[1]})
не надо так)

2022-12-27 20:22 UTC, alexander-sidorov commented on hw/eugene_vavilov/lesson12/lesson.py
>          self.http_version: str = (response[0:8]).strip(" \n")
почему именно 0:8 ?

2022-12-27 20:22 UTC, alexander-sidorov commented on hw/eugene_vavilov/lesson12/lesson.py
> +            self.headers.update({i[0]: i[1]})
не надо так)

2022-12-28 08:40 UTC, EvgVavilov commented on hw/eugene_vavilov/lesson12/lesson.py
> +        url = urlparse(url)
Бог с этой 10)) Вместо прописи и дебага 40-а дополнительных условий пойду что-нибудь ещё почитаю ХД

2022-12-28 08:42 UTC, alexander-sidorov commented on hw/eugene_vavilov/lesson12/lesson.py
> +        url = urlparse(url)
Но ведь... это же... развивать алгоритмическое мышление...

А не хочешь ли почитать тогда про регулярные выражения и как с помощью них решить эту задачу?

2022-12-28 08:42 UTC, EvgVavilov commented on hw/eugene_vavilov/lesson12/lesson.py
> +            self.headers.update({_[0]: _[1]})
Оптимизировал. Но не понял где ТЗ нарушил))

2022-12-28 08:44 UTC, EvgVavilov commented on hw/eugene_vavilov/lesson12/lesson.py
> +            self.headers.update({i[0]: i[1]})
Я немного оптимизировал, но от replace полностью отказаться не могу

2022-12-28 08:45 UTC, EvgVavilov commented on hw/eugene_vavilov/lesson12/lesson.py
>          self.http_version: str = (response[0:8]).strip(" \n")
Исправил

2022-12-28 08:45 UTC, EvgVavilov commented on hw/eugene_vavilov/lesson12/lesson.py
> +            self.headers.update({i[0]: i[1]})
Здесь тоже оптимизировал

2022-12-28 08:48 UTC, EvgVavilov commented on hw/eugene_vavilov/lesson12/lesson.py
> +        body_end = response.find("}")
Я добавил условие на случай пустого тела и улучшил читаемость кода. Не искать фигурные скобки не могу.

2022-12-28 08:51 UTC, alexander-sidorov requested changes

2022-12-28 08:51 UTC, alexander-sidorov commented on hw/eugene_vavilov/lesson12/lesson.py
> +        if "{" in response:
окей, вот еще пример ответа для теста:

```
HTTP/1.1 200 OK
Content-length: 26

ODQzZjg3}N2Iz{ODdiNDc1NA==
```

2022-12-28 08:52 UTC, alexander-sidorov commented on hw/eugene_vavilov/lesson12/lesson.py
> +        body_end = response.find("}")
дело не в этом: твой код заточен под определенный ответ, со "скобками", а я веду к тому, что содержимое тела нас не касается в этой задаче

2022-12-28 08:55 UTC, alexander-sidorov commented on hw/eugene_vavilov/lesson12/lesson.py
> +            self.headers.update({i[0]: i[1]})
можешь:

```
#1 
"Accept: xxx".split(": ") == ["Accept", "xxx"]

#2 
headers = {}
headers["key"] = "value"
```

2023-01-02 12:21 UTC, EvgVavilov commented on hw/eugene_vavilov/lesson12/lesson.py
> +        body_end = response.find("}")
Исправил

2023-01-02 12:21 UTC, EvgVavilov commented on hw/eugene_vavilov/lesson12/lesson.py
> +            self.headers.update({i[0]: i[1]})
Исправил

2023-01-02 12:21 UTC, EvgVavilov commented on hw/eugene_vavilov/lesson12/lesson.py
> +        if "{" in response:
Тест добавил, код исправил

2023-01-04 12:42 UTC, alexander-sidorov approved these changes

2023-01-04 12:44 UTC, merged