Eugene lubimov lesson 14
alexander-sidorov/m-pt1-58-22 pull request #153
Opened 2023-01-04 18:58 UTC by 05TELO

2023-01-06 14:59 UTC, 05TELO commented
был конфликт слияния не разрулевыемый,но вроде получилось исправить))но это не точно..

2023-01-07 15:48 UTC, alexander-sidorov requested changes

2023-01-07 15:48 UTC, alexander-sidorov commented on app_eugene_lubimov/templates/app_eugene_lubimov/task01.html
> +</html>
добавь пожалуйста пустую строку в конец, чтобы не было этого кирпича

2023-01-08 12:04 UTC, alexander-sidorov approved these changes

2023-01-08 12:08 UTC, merged