Eugene-vavilov-lesson14
alexander-sidorov/m-pt1-58-22 pull request #156
Opened 2023-01-06 12:50 UTC by EvgVavilov

2023-01-07 15:43 UTC, alexander-sidorov requested changes

2023-01-07 15:43 UTC, alexander-sidorov commented on app_eugene_vavilov/admin.py
> +from django.contrib import admin  # noqa F401
этот файл можно сделать пустым

2023-01-07 15:43 UTC, alexander-sidorov commented on app_eugene_vavilov/models.py
> +from django.db import models  # noqa F401
этот файл можно сделать пустым

2023-01-07 15:43 UTC, alexander-sidorov commented on app_eugene_vavilov/templates/app_eugene_vavilov/lesson04.html
> +</html>
надо добавить пустую строку в конец, чтобы не висел этот кирпич

2023-01-07 15:43 UTC, alexander-sidorov commented on app_eugene_vavilov/tests.py
> +from django.test import TestCase  # noqa F401
этот файл можно сделать пустым

2023-01-07 15:43 UTC, alexander-sidorov commented on app_eugene_vavilov/urls.py
> +urlpatterns = [  # noqa
почему `# noqa`? что ломается?

2023-01-07 15:43 UTC, alexander-sidorov commented on app_eugene_vavilov/views.py
> +from django.shortcuts import render  # noqa I005
а тут зачем `# noqa`?

2023-01-10 22:11 UTC, EvgVavilov commented on app_eugene_vavilov/admin.py
> +from django.contrib import admin  # noqa F401
Исправил

2023-01-10 22:11 UTC, EvgVavilov commented on app_eugene_vavilov/models.py
> +from django.db import models  # noqa F401
Исправил

2023-01-10 22:11 UTC, EvgVavilov commented on app_eugene_vavilov/templates/app_eugene_vavilov/lesson04.html
> +</html>
Исправил

2023-01-10 22:11 UTC, EvgVavilov commented on app_eugene_vavilov/tests.py
> +from django.test import TestCase  # noqa F401
Исправил

2023-01-10 22:14 UTC, EvgVavilov commented on app_eugene_vavilov/urls.py
> +urlpatterns = [  # noqa
Исправил. Flake8 ругался, сообщал что файл мог быть отредактирован с black, а я не сразу понял что black по умолчанию проверяет папку hw

2023-01-10 22:15 UTC, EvgVavilov commented on app_eugene_vavilov/views.py
> +from django.shortcuts import render  # noqa I005
Исправил. Раньше flake ругался, сейчас не ругается. Почему не знаю

2023-01-11 13:55 UTC, alexander-sidorov approved these changes

2023-01-11 13:59 UTC, merged