There is a list of students on the main page
alexander-sidorov/m-pt1-58-22 pull request #166
Opened 2023-01-08 10:34 UTC by Mikhailiuk-Dmitriy

2023-01-08 11:49 UTC, alexander-sidorov requested changes
Спасибо, очень круто!

Попрошу еще только добавить Заголовок на страницу с названием группы, чтобы не голый список был.

И, еще, сможешь ли вынести шаблон как базовый? я бы попросил положить его в `project/templates/`, настроить соответствующе `settings.py`.

Вот тут подробнее: [Template inheritance](https://docs.djangoproject.com/en/4.1/ref/templates/language/#template-inheritance)

2023-01-09 15:58 UTC, alexander-sidorov requested changes

2023-01-09 15:58 UTC, alexander-sidorov commented on project/settings.py
> +        "DIRS": ["project/templates"],
попробуй использовать переменную `DIR_REPO` ? чтобы не хардкодить путь

2023-01-09 15:58 UTC, alexander-sidorov commented on project/settings.py
> +    "project/static",
аналогично, попробуй определить путь относительно переменной `DIR_REPO`

вот тут можно почитать про [pathlib.Path](https://docs.python.org/3.10/library/pathlib.html)

2023-01-09 15:58 UTC, alexander-sidorov commented on project/templates/project/base.html
> +    <title>Title</title>
добавь плз [viewport](https://developer.mozilla.org/ru/docs/Glossary/Viewport)

2023-01-09 15:58 UTC, alexander-sidorov commented on project/templates/project/base.html
> +<ol class="rectangle">
как насчёт подрубить [Bootstrap](https://getbootstrap.com/)? :)

2023-01-09 19:02 UTC, Mikhailiuk-Dmitriy commented on project/settings.py
> +        "DIRS": ["project/templates"],
я насколько понял переменная DIR_REPO хранит путь к папке проекта не зависимо от платформы, 
как правильно ее использовать в "DIRS" или STATICFILES_DIRS прописать путь в  [DIR_REPO  /  'project / templates'] или в подключаемой команде {% extends 'templates/project/base.html' %}?

2023-01-09 19:07 UTC, Mikhailiuk-Dmitriy commented on project/templates/project/base.html
> +<ol class="rectangle">
подключать только Bootstrap css или Bootstrap js тоже можно)

2023-01-10 15:12 UTC, alexander-sidorov commented on project/settings.py
> +        "DIRS": ["project/templates"],
речь только про `settings.py`. и да, ты догадался правильно насчет пути

2023-01-10 15:13 UTC, alexander-sidorov commented on project/templates/project/base.html
> +<ol class="rectangle">
всё подключай) явно кому-нибудь понадобится, вроде @VadimZharsky уже использует на своей странице

2023-01-11 13:16 UTC, alexander-sidorov approved these changes

2023-01-11 13:17 UTC, merged