Eugene Lubimov Lesson 15
alexander-sidorov/m-pt1-58-22 pull request #178
Opened 2023-01-11 16:59 UTC by 05TELO

2023-01-12 13:52 UTC, alexander-sidorov requested changes

2023-01-12 13:52 UTC, alexander-sidorov commented on app_eugene_lubimov/views.py
> +        "data": list(result),
а что будет, если не будешь в list конвертировать?

2023-01-12 13:52 UTC, alexander-sidorov commented on app_eugene_lubimov/views.py
> +        "data": bool(result),
что будет, если не будешь в bool конвертировать?

2023-01-12 13:52 UTC, alexander-sidorov commented on app_eugene_lubimov/views.py
> +        "data": bool(result),
что будет, если не будешь в bool конвертировать?

2023-01-12 13:52 UTC, alexander-sidorov commented on app_eugene_lubimov/views.py
> +    number = int(request.GET["n"])
вроде как `n` может любым числом быть, поэтому я бы предложил конвертировать во float

2023-01-12 13:52 UTC, alexander-sidorov commented on app_eugene_lubimov/views.py
> +    seq = request.GET["s"][1:-1].split(", ")
интересное решение. А если строка придёт?

http://localhost:8000/~/eugene_lubimov/lesson04/task05/?s=abcdef

2023-01-12 13:52 UTC, alexander-sidorov commented on app_eugene_lubimov/urls.py
> +    path("lesson04/task05/", views.handle_task_01_boundary),
`lesson06/` ?

2023-01-12 13:52 UTC, alexander-sidorov commented on app_eugene_lubimov/views.py
> +    return HttpResponse(json.dumps(payload), content_type="application/json")
используй `JsonResponse(payload)`, меньше кода будет

2023-01-12 13:52 UTC, alexander-sidorov commented on app_eugene_lubimov/views.py
> +        return HttpResponse(" ")
вот юзер удивится ))

2023-01-12 13:52 UTC, alexander-sidorov commented on app_eugene_lubimov/views.py
> +    seq1, seq2 = request.GET["s1"][1:-1].split(", "), request.GET["s1"][
вот это `request.GET[xxx][1:-1].split(", ")` повторяется уже 6 раз, вроде? Если код больше 1 раза повторяется, то это сразу повод вынести его в отдельную функцию)

2023-01-16 11:17 UTC, alexander-sidorov requested changes

2023-01-16 11:17 UTC, alexander-sidorov commented on app_alexander_sidorov/views.py
> +            return JsonResponse(
воу воу палехчи )))

2023-01-16 11:21 UTC, 05TELO commented on app_alexander_sidorov/views.py
> +            return JsonResponse(
эт я конфликты исправлял)

2023-01-16 19:52 UTC, 05TELO commented on app_alexander_sidorov/views.py
> +            return JsonResponse(
Хм,а как это исправить меньшей кровью?

2023-01-16 20:24 UTC, alexander-sidorov requested changes

2023-01-16 20:24 UTC, alexander-sidorov commented on app_alexander_sidorov/views.py
> +            return JsonResponse(
да глянуть этот ПР и удалить этот код: строки 23~28 дублируют 29~35

оставить одну копию вместо двух

2023-01-18 21:47 UTC, alexander-sidorov requested changes

2023-01-18 21:47 UTC, alexander-sidorov commented on app_eugene_lubimov/views.py
> +    def __int__(self):
`__init__` ?

2023-01-21 00:59 UTC, alexander-sidorov approved these changes

2023-01-21 00:59 UTC, merged