Vladislav Yurenya Lesson 15
alexander-sidorov/m-pt1-58-22 pull request #185
Opened 2023-01-11 17:54 UTC by varfalomey777

2023-01-12 13:38 UTC, alexander-sidorov requested changes

2023-01-12 13:38 UTC, alexander-sidorov commented on app_vladislav_yurenya/templates/app_vladislav_yurenya/hello.html
> +  <a href="{% url 'money' %}">Task money</a><br>
@varfalomey777 Владислав, погугли пожалуйста в сторону django url namespaces, чтобы имена урлов превратились из `'money'` в `'vladislav_yurenya:money'`

2023-01-12 13:38 UTC, alexander-sidorov commented on app_vladislav_yurenya/templates/app_vladislav_yurenya/task02.html
> +<form action="/~/vladislav_yurenya/lesson04/task02/" method="get">
тогда и здесь используй уже url names :)

2023-01-12 13:38 UTC, alexander-sidorov commented on app_vladislav_yurenya/views.py
> +    return HttpResponse(json.dumps(payload), content_type="application/json")
попробуй вместо `HttpResponse(...)` использовать сразу `JsonResponse(payload)`?

2023-01-12 15:08 UTC, varfalomey777 commented on app_vladislav_yurenya/templates/app_vladislav_yurenya/hello.html
> +  <a href="{% url 'money' %}">Task money</a><br>
окей,попробую

2023-01-12 15:32 UTC, varfalomey777 commented on app_vladislav_yurenya/templates/app_vladislav_yurenya/hello.html
> +  <a href="{% url 'money' %}">Task money</a><br>
у меня вопрос нарисовался, подскажите пожалуйста , мне во views создать словарь с именем пути и потом с помощью for выводить ссылки?
или мыслить в сторону slug?

2023-01-16 10:25 UTC, alexander-sidorov requested changes

2023-01-16 10:25 UTC, alexander-sidorov commented on project/urls.py
> +            "app_vladislav_yurenya.urls", namespace="app_vladislav_yurenya"
а попробуй плз в своём `urls.py` добавить глобальную переменную `app_name` со значением `"app_vladislav_yurenya"`, а этот файл оставить как есть?

2023-01-16 10:25 UTC, alexander-sidorov commented on project/urls.py
> +            "app_vladislav_yurenya.urls", namespace="app_vladislav_yurenya"
у Вадима Жарского есть пример

2023-01-16 16:17 UTC, varfalomey777 commented on project/urls.py
> +            "app_vladislav_yurenya.urls", namespace="app_vladislav_yurenya"
Если я вас правильно понял , то в путях приложения есть глобальная переменная

2023-01-22 09:57 UTC, alexander-sidorov approved these changes

2023-01-22 09:57 UTC, merged