Vadim zharski lesson15
alexander-sidorov/m-pt1-58-22 pull request #186
Opened 2023-01-11 18:52 UTC by VadimZharsky

2023-01-16 10:22 UTC, alexander-sidorov requested changes

2023-01-16 10:22 UTC, alexander-sidorov commented on app_vadim_zharski/services/average_finder.py
> +                self.__numbers = json.load(f)
есть ошчушчэние, что это копипаст кода из `file_reader()` :) а зачем тогда делать целый сервис в ООП стиле, если не переиспользовать его код?

2023-01-16 10:41 UTC, VadimZharsky commented
Добрый день!
Согласен полностью, file_reader() и file_append() имеют почти одинаковую
реализацию.
Изначально было так: file_append(self, num: int = None) и file_append не
было.
Всё работало прекрасно, но mypy ругался на неверный тип, что инт не может
быть None.
Поэтому пришлось дублировать код.



On Mon, Jan 16, 2023, 1:22 PM Alexander Sidorov ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In app_vadim_zharski/services/average_finder.py
> <https://github.com/alexander-sidorov/m-pt1-58-22/pull/186#discussion_r1071064469>
> :
>
> > +            Path(__file__).parent.parent.parent
>
> +            / ".artifacts/vadim_zharski.json"
>
> +        )
>
> +
>
> +    def file_reader(self) -> dict:
>
> +        try:
>
> +            with self.__file_path.open("r") as f:
>
> +                self.__numbers = json.load(f)
>
> +        except (OSError, json.JSONDecodeError):
>
> +            self.__numbers = []
>
> +        return self.__content()
>
> +
>
> +    def file_append(self, num: int) -> dict:
>
> +        try:
>
> +            with self.__file_path.open("r") as f:
>
> +                self.__numbers = json.load(f)
>
>
> есть ошчушчэние, что это копипаст кода из file_reader() :) а зачем тогда
> делать целый сервис в ООП стиле, если не переиспользовать его код?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/alexander-sidorov/m-pt1-58-22/pull/186#pullrequestreview-1249905141>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKHW3LIJMDQO5U3OY2FM4ILWSUOPDANCNFSM6AAAAAATYL3UEY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-01-25 13:25 UTC, alexander-sidorov requested changes

2023-01-25 13:25 UTC, alexander-sidorov commented on pyproject.toml
> +psycopg2 = "^2.9.5"
удоляй) пожалуйста

2023-01-25 13:25 UTC, alexander-sidorov commented on pyproject.toml
> +psycopg2 = "^2.9.5"
и `binary` тоже

2023-02-01 16:14 UTC, alexander-sidorov approved these changes

2023-02-01 16:14 UTC, merged