json response on /students/
alexander-sidorov/m-pt1-58-22 pull request #188
Opened 2023-01-12 15:13 UTC by karmaxa

2023-01-12 15:42 UTC, alexander-sidorov requested changes

2023-01-12 15:42 UTC, alexander-sidorov commented on app_main/views.py
> +    return HttpResponse(json.dumps(payload), content_type="application/json")
а заюзай сразу пожалуйста `JsonResponse`?

```python
return JsonResponse(payload)
```

2023-01-12 15:42 UTC, alexander-sidorov commented on project/urls.py
> +    path("students/", students_listdict),
алфавит)

о! попрошу добавить префикс /api/:

```python
    path("api/students/", students_listdict),
```

2023-01-12 15:43 UTC, alexander-sidorov commented on project/urls.py
> +    path("students/", students_listdict),
нащот алфавита: поможет

1. плагин к пайчарму `String Manipulation`
2. повесить хоткей на `String Manipulation : Sort lines .. `

2023-01-16 10:16 UTC, alexander-sidorov requested changes

2023-01-16 12:53 UTC, tgrx approved these changes

2023-01-16 12:53 UTC, alexander-sidorov approved these changes

2023-01-16 12:53 UTC, merged