Eugene vavilov lesson18
alexander-sidorov/m-pt1-58-22 pull request #204
Opened 2023-01-20 18:49 UTC by EvgVavilov

2023-01-23 17:37 UTC, alexander-sidorov requested changes
Насчёт сохранения введённого фильтра:

вот пример решения: https://stackoverflow.com/a/813474

а так же задание намекает на то, что раз надо "сохранять", то для этого нам и пригодится база данных)

2023-01-23 17:37 UTC, alexander-sidorov commented on app_eugene_vavilov/models.py
> +    name: models.CharField = models.CharField(max_length=20)
вот [эти чуваки](https://newsnn.ru/news/2009-04-12/samoe-dlinnoe-v-mire-chelovecheskoe-imya-sostoit-iz-1478-bukv-2446696) сейчас заплакали

2023-01-23 17:37 UTC, alexander-sidorov commented on app_eugene_vavilov/models.py
> +    number: models.IntegerField = models.IntegerField()
в каждое поле добавь пожалуйста настройки `blank=True, null=True`

2023-01-24 23:06 UTC, EvgVavilov commented on app_eugene_vavilov/models.py
> +    name: models.CharField = models.CharField(max_length=20)
Я достаточно увеличил максимальный предел чтоб мужик мог ещё фамилию указать)

2023-01-24 23:07 UTC, EvgVavilov commented on app_eugene_vavilov/models.py
> +    number: models.IntegerField = models.IntegerField()
Добавил

2023-01-24 23:08 UTC, EvgVavilov commented
Я условия задачи выполнил, но без изменений в базу данных

2023-01-25 13:28 UTC, alexander-sidorov commented on app_eugene_vavilov/views.py
> +saved_filter = {"search": ""}
так ведь после перезагрузки сервера это пропадёт...

2023-01-25 13:35 UTC, alexander-sidorov requested changes
Женя, смотри, создаю контакты:

<img width="308" alt="image" src="https://user-images.githubusercontent.com/76160017/214576984-54f5e4b9-a16c-4336-9b94-b389d9ce4cd5.png">

Хочу отфильровать по "а" и вижу:
<img width="220" alt="image" src="https://user-images.githubusercontent.com/76160017/214577205-c2cf9f6b-810d-4a63-9116-4eceecfa7be2.png">

Но разве только в этих двух есть буква "а"?)

2023-01-27 14:52 UTC, alexander-sidorov requested changes
Женя, верни пожалуйста назад файл `/.env.dist`

2023-02-01 16:04 UTC, alexander-sidorov approved these changes

2023-02-01 16:04 UTC, merged