Vladislav Yurenya Lesson 17
alexander-sidorov/m-pt1-58-22 pull request #209
Opened 2023-01-23 11:12 UTC by varfalomey777

2023-01-23 14:29 UTC, alexander-sidorov requested changes
Владислав, алгоритм рабочий, но неудобный: выходит, чтобы пользоваться контактами, надо по двум страницам ходить? Попробуй сделать всё на одной странице.

2023-01-24 12:14 UTC, varfalomey777 commented
Я понял только как реализовать через redirect,но как на одной странице...

2023-01-24 23:04 UTC, alexander-sidorov requested changes

2023-01-24 23:04 UTC, alexander-sidorov commented on app_vladislav_yurenya/views.py
> +class Contact(FormView, ListView):
предлагаю сделать или 2 разных вьюхи, или одну с нужными миксинами

2023-01-25 07:55 UTC, varfalomey777 commented on app_vladislav_yurenya/views.py
> +class Contact(FormView, ListView):
Как я понимаю создаю 3 класса, два функциональных и 3 который их принимает?
Надеюсь правильно понял про миксины😅

2023-01-25 13:13 UTC, alexander-sidorov commented on app_vladislav_yurenya/views.py
> +class Contact(FormView, ListView):
Не совсем. Дело в том, что наследование двух вьюх приводит к коллизиям на уровне их алгоритмов: к примеру, GET для `FormView` совсем не то же самое, что для `ListView`.

Предлагаю почитать про такую штуку, как `Mixin`, и посмотреть внутрь дженерик вьюх за примерами.

В любом случае, решение будет нетривиальное, как и в любом подобном случае: когда в одну сущность набивается несколько независимых функционалов.

2023-01-25 13:18 UTC, alexander-sidorov requested changes
Владислав, скачал себе твою ветку, применил миграции:
<img width="663" alt="image" src="https://user-images.githubusercontent.com/76160017/214573277-9eea34bc-3beb-41cf-b82c-f9576eab9680.png">

Захожу на [страницу задания с контактами](http://127.0.0.1:8000/~/vladislav_yurenya/contacts/) и вижу:
<img width="643" alt="image" src="https://user-images.githubusercontent.com/76160017/214573048-3efa21a1-504c-46c2-8ecd-491e2540a71c.png">

2023-01-28 13:16 UTC, alexander-sidorov approved these changes

2023-01-28 13:23 UTC, merged