Eugene Lubimov Lesson 19
alexander-sidorov/m-pt1-58-22 pull request #226
Opened 2023-01-26 07:51 UTC by 05TELO

2023-01-26 08:02 UTC, alexander-sidorov requested changes

2023-01-26 08:02 UTC, alexander-sidorov commented on app_eugene_lubimov/templates/app_eugene_lubimov/contacts.html
> +        <form action="delete/" method="post">
Кажется, айди всё же нужно передавать

2023-01-26 13:14 UTC, 05TELO commented
Саша нужна помощь,при нажатии кнопки update просто затирает контакт,но если руками прописать id/update все норм кидает на  форму и работает..понимаю что дело в какойто мелочи с урлами ,но хоть убей не вижу где

2023-01-26 13:20 UTC, alexander-sidorov commented
Женя, привет.Насколько я вижу, на "контакт/апдейт" пост запросом отправляется НИЧЕГО - а в этом случае контакт и может затереться.С апдейт вью предлагаю работать так: сделать кнопку/ссылку на "контакт/ид/апдейт", чтобы эта ссылка открывалась ГЕТ запросом.Тогда джанго отрисует новую страницу, с шаблоном с ЗАПОЛНЕННОЙ формой, где можно уже подправить инфу, и апдейтить (пост запрос на "контакт/ид/апдейт"), сохранив то что есть.{{form}} вроде за это всё будет отвечать--------Alexander SidorovOn 26 Jan 2023, at 16:14, Yauheni ***@***.***> wrote:﻿
Саша нужна помощь,при нажатии кнопки update просто затирает контакт,но если руками прописать id/update все норм кидает на  форму и работает..понимаю что дело в какойто мелочи с урлами ,но хоть убей не вижу где

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because your review was requested.Message ID: ***@***.***>

2023-01-26 14:01 UTC, 05TELO commented
> Женя, привет.Насколько я вижу, на "контакт/апдейт" пост запросом отправляется НИЧЕГО - а в этом случае контакт и может затереться.С апдейт вью предлагаю работать так: сделать кнопку/ссылку на "контакт/ид/апдейт", чтобы эта ссылка открывалась ГЕТ запросом.

Спасибо,сделал

2023-01-27 14:44 UTC, alexander-sidorov approved these changes

2023-01-27 14:44 UTC, merged