karman
alexander-sidorov/m-pt1-58-22 pull request #25
Opened 2022-12-06 00:03 UTC by karmaxa

lesson05 done

2022-12-06 17:02 UTC, alexander-sidorov commented on hw/mikita_karmanaw/lesson06/tasks.py
> +CITIES = {
```python
from hw.alexander_sidorov.helpers import CITIES
```

вместо тысячи слов...

2022-12-06 17:03 UTC, alexander-sidorov commented on hw/mikita_karmanaw/lesson06/tasks.py
> +            ((CITIES[city][0] - CITIES[town][0]) * 110) ** 2
есть ошчушчэние, что в ТЗ размер дуги по параллели равен 111 км :)

2022-12-06 17:05 UTC, alexander-sidorov commented on hw/mikita_karmanaw/lesson06/tasks.py
> +        dist = sqrt(
я тоже считаю, что `ECE001 Expression is too complex` и предложу воспользоваться подсказкой из ТЗ

2022-12-06 17:06 UTC, alexander-sidorov commented on hw/mikita_karmanaw/lesson06/tasks.py
> +            ((CITIES[town][0] - CITIES[route[route.index(town) - 1]][0]) * 110)
есть ошчушчэние, что этот код где-то я уже видел... 🤔

наверное в строке 66 ???

2022-12-06 17:08 UTC, alexander-sidorov commented on hw/mikita_karmanaw/lesson06/tasks.py
> +            ** 2
оно (выражение) реально адово выглядит, да ещё и при отладке будет дополнительная боль. Всё-таки тоже предложу воспользоваться подсказкой из ТЗ.

2022-12-07 10:27 UTC, alexander-sidorov requested changes
ещё проверочку:
- `set.issuperset`
- `dict.__getitem__`

2022-12-07 10:31 UTC, alexander-sidorov commented on hw/mikita_karmanaw/lesson06/tasks.py
> +    for elem in lesser:
вообще задача по ТЗ решена, но как стремящемуся сокращать код замечу, что эта задача решается в 1 строку, без if-ов. Помогут нам в этом функции sum и zip

2022-12-07 10:32 UTC, alexander-sidorov commented on hw/mikita_karmanaw/lesson06/tasks.py
> +        dist_dict.update({town: dist})
рекомендую юзать присваивание по ключу, так будет всем привычнее:

```python
dist_dict[town] = dist
```

2022-12-07 10:32 UTC, alexander-sidorov commented on hw/mikita_karmanaw/lesson06/tasks.py
> +        dist_1 = (CITIES[town][1] - previous_town_cords[1]) * 65
ты ж писал этот код уже? в строках 36-38

2022-12-09 20:31 UTC, karmaxa commented
Сказал, что впадлу переписывать код, по итогу всё равно переписал))
пятый и шестой готовы

2022-12-10 13:28 UTC, alexander-sidorov approved these changes

2022-12-10 13:28 UTC, merged