Mikita Karmanaw lesson 25
alexander-sidorov/m-pt1-58-22 pull request #276
Opened 2023-02-15 22:52 UTC by karmaxa

2023-02-16 10:05 UTC, alexander-sidorov requested changes
взял тут твою ветку, удалил базу, создал ее заново, промигрировал, всё хорошо, создал суперюзера. Зашел в твоё приложение, залогинился и... добрейший вечерочек! ))

<img width="800" alt="image" src="https://user-images.githubusercontent.com/76160017/219334173-4d8d8ccb-d88c-4312-98e4-dd84a343c90b.png">

2023-02-16 10:13 UTC, karmaxa commented on app_mikita_karmanaw/models.py
> +    relations: Any = models.ManyToManyField(
1. супер-юзерам профиль не нужен) но окей, это поправлю, сложно быть не должно
2. как-то не подумал, что в модели может быть поле relations, даже смешно стало теперь :D
жаль, что самые очевидные имена уже заняты, придётся включать фантазию

2023-02-16 14:05 UTC, karmaxa commented
Ну всё, должно работать офигенно: профиль создаётся, если нужно, теги есть, работают, не связаны с профилем или юзером, есть удобные (на мой взгляд) инструменты работы с ними (создание, изменение, удаление), легко добавляются или удаляются теги контактов, доступен поиск по тегу и совместный по тегу и имени, короче, кайфово, я думаю

2023-02-17 14:35 UTC, alexander-sidorov approved these changes

2023-02-17 14:35 UTC, merged