Lubimov added package Lesson06
alexander-sidorov/m-pt1-58-22 pull request #29
Opened 2022-12-07 10:25 UTC by 05TELO

2022-12-07 10:36 UTC, alexander-sidorov requested changes

2022-12-07 10:36 UTC, alexander-sidorov commented on hw/eugene_lubimov/lesson05/stdtypes_test.py
> +def test_list() -> None:
ты же писал это уже в другом пулл-реквесте? это же не ДЗ 6?

2022-12-07 10:36 UTC, alexander-sidorov commented on hw/eugene_lubimov/lesson06/tasks.py
> +#from hw.alexander_sidorov.helpers import CITIES
раскомментируй плз, давай разберемся, почему импорт не работает

2022-12-07 10:36 UTC, alexander-sidorov commented on hw/eugene_lubimov/lesson06/tasks.py
> +    return sum(map(lambda x: x[0] != x[1], zip(seq1, seq2))) + abs(len(seq1) - len(seq2))
map и lambda тут не нужны: sum умеет с коллекциями и генераторами работать сразу

2022-12-07 11:07 UTC, 05TELO commented on hw/eugene_lubimov/lesson05/stdtypes_test.py
> +def test_list() -> None:
это я сделал новую ветку дял 6го дзб зря?

2022-12-07 11:21 UTC, 05TELO commented on hw/eugene_lubimov/lesson06/tasks.py
> +    return sum(map(lambda x: x[0] != x[1], zip(seq1, seq2))) + abs(len(seq1) - len(seq2))
исправил

2022-12-07 11:21 UTC, 05TELO commented on hw/eugene_lubimov/lesson06/tasks.py
> +#from hw.alexander_sidorov.helpers import CITIES
раскомментировал

2022-12-08 20:21 UTC, alexander-sidorov commented on hw/eugene_lubimov/lesson05/stdtypes_test.py
> +def test_list() -> None:
ветку новую для нового задания - хорошо!

только отпочковывать её надо было от `main`, обновлённой

а не от ветки с 5 заданием)

продолжай как есть, мб будет некритично

2022-12-08 20:22 UTC, alexander-sidorov approved these changes

2022-12-08 20:25 UTC, merged