создана папка и добавлен в неё файл
alexander-sidorov/m-pt1-58-22 pull request #3
Opened 2022-11-25 18:53 UTC by andreigalardo

2022-11-30 12:23 UTC, alexander-sidorov approved these changes

2022-12-01 01:29 UTC, alexander-sidorov requested changes

2022-12-01 01:29 UTC, alexander-sidorov commented on hw/andrei_karpuk/__init__.py
> +
сделай плз этот файл максимально пустым, чтобы вообще ничего в нём не было

2022-12-01 17:17 UTC, alexander-sidorov commented on hw/andrei_karpuk/__init__.py
> +
сразу напишу, как файл сделать пустым вообще:

1. в консоли переходи в папку, где лежит файл, который надо сделать пустым.
2. находясь в этой папке, запускай следующую команду ТОЧНО ТАК как напишу) вот:

```bash
python -c 'with open("__init__.py", "w"): pass'
```

вместо `__init__.py` подставляй тот файл, который надо сделать пустым

2022-12-10 13:07 UTC, alexander-sidorov requested changes
добавь пожалуйста пустой файл

`hw/andrei_karpuk/lesson04/__init__.py`

2022-12-10 13:07 UTC, alexander-sidorov commented on hw/andrei_karpuk/lesson04/lecture_test.py
> +
между импортами своими не надо делать пустые строки

2022-12-10 13:07 UTC, alexander-sidorov commented on hw/andrei_karpuk/lesson04/lecture_test.py
> +assert task_01_money(1, 2, 3) == Decimal("3.06")
все проверки должны быть убраны под тест-функцию

```python
def test_....
```

2022-12-10 13:07 UTC, alexander-sidorov commented on hw/andrei_karpuk/lesson04/lecture.py
> +    return (rubles + coin/100) * amount
Нужно чтобы результат тоже был типа Decimal, а тут он float

2022-12-10 13:07 UTC, alexander-sidorov commented on hw/andrei_karpuk/lesson04/lecture.py
> +    return +1 if task_02_sign(number) > 0 else(-1 if task_02_sign(number) < 0 else 0)
эта функция в принципе не работает

2022-12-10 13:07 UTC, alexander-sidorov commented on hw/andrei_karpuk/lesson04/lecture.py
> +    if s1 + s2 > s3 and s2 + s3 > s1 and s3 + s1 > s2:
результат выражения `s1 + s2 > s3 and s2 + s3 > s1 and s3 + s1 > s2` — уже типа `bool`, и его надо сразу и возвращать, без `if..else`

2022-12-10 13:07 UTC, alexander-sidorov commented on hw/andrei_karpuk/lesson04/lecture.py
> +    if string == string[::-1]:
тоже сразу возвращай bool значение, без `if..else`

2022-12-10 13:07 UTC, alexander-sidorov commented on hw/andrei_karpuk/lesson04/lecture_test.py
> +from lecture import task_01_money
неизвестный импорт

`from hw.andrei_karpuk.leson04.lecture import ...`

2022-12-10 16:47 UTC, andreigalardo commented on hw/andrei_karpuk/lesson04/lecture_test.py
> +
Файл добавил , пустые строки убрал

2022-12-10 16:47 UTC, andreigalardo commented on hw/andrei_karpuk/lesson04/lecture_test.py
> +assert task_01_money(1, 2, 3) == Decimal("3.06")
убрал проверки под функции

2022-12-10 16:47 UTC, andreigalardo commented on hw/andrei_karpuk/lesson04/lecture.py
> +    return (rubles + coin/100) * amount
поправил

2022-12-10 16:48 UTC, andreigalardo commented on hw/andrei_karpuk/lesson04/lecture.py
> +    return +1 if task_02_sign(number) > 0 else(-1 if task_02_sign(number) < 0 else 0)
переделал

2022-12-10 16:48 UTC, andreigalardo commented on hw/andrei_karpuk/lesson04/lecture.py
> +    if s1 + s2 > s3 and s2 + s3 > s1 and s3 + s1 > s2:
сделано

2022-12-10 16:48 UTC, andreigalardo commented on hw/andrei_karpuk/lesson04/lecture.py
> +    if string == string[::-1]:
сделано

2022-12-10 16:49 UTC, andreigalardo commented on hw/andrei_karpuk/lesson04/lecture_test.py
> +from lecture import task_01_money
есть нюанс , если так вводить путь импорта , то оно вообще не определяет путь почему-то
![image](https://user-images.githubusercontent.com/119035052/206865960-e65deafc-9955-410f-88ce-546c84d1f753.png)
И почему-то подчёркивает assert первый в каждой из функций

2022-12-11 17:29 UTC, alexander-sidorov approved these changes

2022-12-11 17:29 UTC, merged