completed task 5
alexander-sidorov/m-pt1-58-22 pull request #30
Opened 2022-12-08 14:26 UTC by AliakseiTsiukhai

2022-12-08 20:18 UTC, alexander-sidorov requested changes
недостаёт проверок на вот эти методы:
- `list.__lt__` / `list.__le__`
- `list.__setitem__`

2022-12-08 20:26 UTC, AliakseiTsiukhai commented
у вас там в helpers написано вроде не надо тестить __le__/__lt__

2022-12-08 20:38 UTC, alexander-sidorov commented
> у вас там в helpers написано вроде не надо тестить **le**/**lt**

а в ТЗ?

2022-12-08 20:52 UTC, AliakseiTsiukhai commented
в ТЗ тоже написано не тестить их

2022-12-08 21:01 UTC, alexander-sidorov commented
у меня тут другая информация)
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/76160017/206566583-19a7a896-a67f-4a71-a5d3-dbb65038c9c1.png">

2022-12-08 21:41 UTC, AliakseiTsiukhai commented
поправил, добавил

2022-12-09 15:58 UTC, alexander-sidorov approved these changes

2022-12-09 16:01 UTC, merged