Vladislav yurenya 06 Dz
alexander-sidorov/m-pt1-58-22 pull request #40
Opened 2022-12-11 12:26 UTC by varfalomey777

2022-12-11 17:23 UTC, alexander-sidorov requested changes
вот этот файл надо удалить:

`hw/vladislav_yurenya/lesson06/.coverage`:

```bash
git config pull.rebase true
git pull
git rm -f hw/vladislav_yurenya/lesson06/.coverage
git commit -m "removed garbage"
```

2022-12-11 17:27 UTC, alexander-sidorov requested changes

2022-12-11 17:27 UTC, alexander-sidorov commented on hw/vladislav_yurenya/lesson06/tasks.py
> +        one = list(CITIES[city])
зачем конвертировать это в list?

2022-12-11 17:27 UTC, alexander-sidorov commented on hw/vladislav_yurenya/lesson06/tasks.py
> +    f(seq1, seq2)
да ну! эта функция в 1 строчку решается, не надо ничего в списки конвертировать и потом их ещё и модифицировать

2022-12-11 17:27 UTC, alexander-sidorov commented on hw/vladislav_yurenya/lesson06/tasks.py
> +        x, y = (one[0] - two[0]) * 111, (one[1] - two[1]) * 65
видел этот код выше, предлагаю копипаст убрать

2022-12-11 20:04 UTC, varfalomey777 commented on hw/vladislav_yurenya/lesson06/tasks.py
> +    f(seq1, seq2)
Пытался через функцию делать , в одну строчку,но не мог ошибки убрать ,гитхаб не пропускал

2022-12-11 20:19 UTC, varfalomey777 commented on hw/vladislav_yurenya/lesson06/tasks.py
> +        one = list(CITIES[city])
пытался делать не через списки, а через кортежи со значениями по ключам, github не пропускал,тест с ошибкой падал

2022-12-11 21:09 UTC, varfalomey777 commented on hw/vladislav_yurenya/lesson06/tasks.py
> +    f(seq1, seq2)
def task_03_hdist(seq1: Sequence, seq2: Sequence) -> int:
    total = 0
    for zip_seq in zip(seq1, seq2):
        if zip_seq[0] != zip_seq[1]:
            total += 1
    if len(seq1) > len(seq2):
        total += len(seq1) - len(seq2)
    if len(seq1) < len(seq2):
        total += len(seq2) - len(seq1)
    return total
  Переписал так ,но выдает небольшое покрытие

2022-12-15 00:10 UTC, alexander-sidorov approved these changes

2022-12-15 00:10 UTC, merged