Lesson5 hw Maksim_Baranau
alexander-sidorov/m-pt1-58-22 pull request #46
Opened 2022-12-12 17:46 UTC by Maksim-Baranau

2022-12-15 13:21 UTC, alexander-sidorov requested changes
не хватает проверок:

- `list.__add__`
- `list.__hash__`
- `list.__lt__`
- `list.__mul__`
- `list.pop`
- `dict.__ior__`
- `dict.__or__`
- `dict.popitem`
- `tuple.index`
- `set.__iand__`
- `set.__ior__`
- `set.__isub__`
- `set.__ixor__`
- `set.__len__`
- `set.__or__`
- `set.__sub__`
- `set.__xor__`
- `set.intersection_update`
- `str.__hash__`
- `str.__mod__`
- `str.format`
- `str.format_map`
- `str.rsplit`
- `str.rstrip`

2022-12-15 15:31 UTC, Maksim-Baranau commented
@alexander-sidorov Исправил, наверное... Объясните пожалуйста, как самому запускать проверки, чтобы каждый раз все это не пушить в мэйн и не смотреть тесты тут

2022-12-18 14:56 UTC, alexander-sidorov commented
> @alexander-sidorov Исправил, наверное... Объясните пожалуйста, как самому запускать проверки, чтобы каждый раз все это не пушить в мэйн и не смотреть тесты тут

надо:

1. установить Python 3.10.8
2. установить Poetry: https://python-poetry.org/docs/#installation
3. запустить `poetry install`
4. запускать проверки и форматировать код: `poetry run make pr`

если остались вопросы "где запускать", направляю на ответ: [README.md](https://github.com/alexander-sidorov/m-pt1-58-22/blob/main/README.md)

_"Иное"_ указываю:
1. ветка должна быть своя
2. за "активированное окружение" отвечает часть команды: `poetry run`

2022-12-18 15:03 UTC, alexander-sidorov requested changes
Не хватает проверок:

- `dict.__ior__`
- `dict.__or__`
- `set.__iand__`
- `set.__iand__`
- `set.__ior__`
- `set.__isub__`
- `set.__ixor__`

2022-12-18 15:03 UTC, alexander-sidorov commented on hw/maksim_baranau/lesson05/stdtypes_test.py
> +    assert {1}.__len__() == 1
> Магические методы напрямую вызывать нельзя

из ТЗ

2022-12-18 20:24 UTC, Maksim-Baranau commented
dict.__ior__ - line 69
dict.__or__  - line 71
set.__iand__ - line 134
set.__ior__ - line 136
set.__isub__ line 122
set.__ixor__  line 138

my_list.__add__([1]) == [2, 4, 1]      =>       my_list + [1] == [2, 4, 1]
assert my_list.__mul__(2) == [2, 4, 2, 4]   =>  my_list *= 2  (line 7)
{1}.__len__() == 1           =>  len(st) == 2 (line 124)

2022-12-18 21:32 UTC, alexander-sidorov approved these changes
отсутствуют проверки:

- `list.__mul__`

2022-12-18 21:34 UTC, merged