lesson09
alexander-sidorov/m-pt1-58-22 pull request #49
Opened 2022-12-14 12:57 UTC by karmaxa

2022-12-14 13:02 UTC, alexander-sidorov requested changes

2022-12-14 13:02 UTC, alexander-sidorov commented on hw/mikita_karmanaw/lesson09/tasks.py
> +        def wrapper(*args: Any, **kwargs: Any) -> Callable:
`wrapper` не возвращает Callable — он возвращает тот тип, который возвращает оригинальная функция.

Вопрос - а как его узнать?

Можно вот так: [ParamSpec](https://docs.python.org/3.10/library/typing.html#typing.ParamSpec)

Но в данном случае можно (разрешаю) поставить `Any`:


```python
def decorator(func: Callable) -> Callable:
    def wrapper(*a: tuple, **k: dict) -> Any:
        return func(*a, **k)
    return wrapper
```

2022-12-14 13:18 UTC, karmaxa commented on hw/mikita_karmanaw/lesson09/tasks.py
> +        def wrapper(*args: Any, **kwargs: Any) -> Callable:
Можно поставить Any на return annotation? Mypy не выдаст опять на такое ошибку no-any-return?

2022-12-15 00:24 UTC, alexander-sidorov requested changes

2022-12-15 00:24 UTC, alexander-sidorov commented on hw/mikita_karmanaw/lesson09/tasks.py
> +            ar = str(args) + str(kwargs)
```python
c = {}

@func_cache_factory(c)
def f(a, b): return a + b

@func_cache_factory(c)
def g(a, b): return a - b

[ f(1, 10) for _ in "123"]
assert f(1, 10) == 11

rg = g(1, 10)
assert rg == -9, rg  # AssertionError: 11

```

2022-12-15 05:49 UTC, karmaxa commented on hw/mikita_karmanaw/lesson09/tasks.py
> +            ar = str(args) + str(kwargs)
вообще я писал этот кэш для работы по типу "одна функция - один архив", подозревал, что именно такие вопросы и могут быть :D 
добавил тесты, изменил код, работает

2022-12-15 09:19 UTC, alexander-sidorov approved these changes

2022-12-15 09:19 UTC, merged