lesson10
alexander-sidorov/m-pt1-58-22 pull request #59
Opened 2022-12-16 16:14 UTC by karmaxa

2022-12-18 12:03 UTC, alexander-sidorov requested changes

2022-12-18 12:03 UTC, alexander-sidorov commented on hw/mikita_karmanaw/lesson10/lesson.py
> +        return None
есть ощущение, что `return` в `__init__` не надо писать

2022-12-18 12:03 UTC, alexander-sidorov commented on hw/mikita_karmanaw/lesson10/lesson.py
> +    def next(self) -> int | None:  # noqa: A003
Сделай плз так, чтобы `next()` при достижении порога всегда возвращал `self.stop`, чтобы тип был `-> int` всегда

2022-12-21 09:52 UTC, karmaxa commented on hw/mikita_karmanaw/lesson10/lesson.py
> +        return None
fixed

2022-12-21 09:53 UTC, karmaxa commented on hw/mikita_karmanaw/lesson10/lesson.py
> +    def next(self) -> int | None:  # noqa: A003
он и так при достижении порога всегда возвращает self.stop, но аннотацию убрал, работает

2022-12-22 20:32 UTC, alexander-sidorov approved these changes

2022-12-22 20:33 UTC, merged