Lubimov create hw directory
alexander-sidorov/m-pt1-58-22 pull request #8
Opened 2022-11-25 18:56 UTC by 05TELO

2022-11-30 12:22 UTC, alexander-sidorov submitted a review, later dismissed

2022-12-01 00:53 UTC, alexander-sidorov requested changes

2022-12-01 00:53 UTC, alexander-sidorov commented on hw/eugene_lubimov/__init__.py
> +
Сделай плз этот `__init__.py` настолько же пустыми, насколько и `lecture.py`: в нём вообще ничего нет, а в `__init__.py` есть пустая строка

2022-12-01 17:06 UTC, alexander-sidorov requested changes

2022-12-01 17:06 UTC, alexander-sidorov commented on hw/eugene_lubimov/lesson04/lecture.py
> +        and side2 < (side1 + side3)
вот так сделай пожалуйста:

```python
return (
        side1 < (side2 + side3)
        and side2 < (side1 + side3)  # noqa: W503
        and side3 < (side1 + side2)  # noqa: W503
    )
```

комментарий `# noqa: W503` - это сигнал Flake8 не ругаться ошибкой `W503 line break before binary operator` на эту строку кода

обрати внимание — между кодом и значком комментария `#` - два пробела

2022-12-02 13:06 UTC, alexander-sidorov commented on hw/eugene_lubimov/lesson04/lecture.py
> +    return Decimal(str((rubles * 100 + coins) * amount / 100))
А зачем конверсия int -> float -> str -> Decimal ?

2022-12-02 13:06 UTC, alexander-sidorov commented on hw/eugene_lubimov/lesson04/lecture.py
> +    new_string = "".join([i for i in string if i.isalpha()]).lower()
А числа нельзя?) "12321" например

2022-12-02 13:34 UTC, 05TELO commented on hw/eugene_lubimov/lesson04/lecture.py
> +    return Decimal(str((rubles * 100 + coins) * amount / 100))
так обрезает до сотых)

2022-12-02 13:34 UTC, 05TELO commented on hw/eugene_lubimov/lesson04/lecture.py
> +    new_string = "".join([i for i in string if i.isalpha()]).lower()
добавить проверку на  пустую строку?

2022-12-02 15:29 UTC, alexander-sidorov commented on hw/eugene_lubimov/lesson04/lecture.py
> +    new_string = "".join([i for i in string if i.isalpha()]).lower()
```python
>>> "123321".isalpha()
False

>>> "123".isalpha()
False
```

и `new_string` будет пустая в обоих случаях, но строка "123321" - палиндром, а "123" - нет

2022-12-02 16:14 UTC, 05TELO commented on hw/eugene_lubimov/lesson04/lecture.py
> +    new_string = "".join([i for i in string if i.isalpha()]).lower()
я понимаю о чем вы.видимо я не правильно понял условие.'1234' можно отнести к не-буквам или нет?)

2022-12-02 22:50 UTC, alexander-sidorov commented on hw/eugene_lubimov/lesson04/lecture.py
> +    new_string = "".join([i for i in string if i.isalpha()]).lower()
`"1234"` конечно не буквы, это цифры)

я бы всё-таки их обрабатывал, а пробелы, запятые и всякое подобное игнорировал

2022-12-02 22:51 UTC, alexander-sidorov commented on hw/eugene_lubimov/lesson04/lecture_test.py
> +    assert not lec.task_04_palindrom("12321")
вот, это как раз стоило бы считать за палиндром - строка с символами, читаются туда-сюда одинаково

2022-12-04 10:14 UTC, alexander-sidorov approved these changes

2022-12-04 10:14 UTC, merged