Alexey-Tuyhai-lesson11-task 3
alexander-sidorov/m-pt1-58-22 pull request #91
Opened 2022-12-21 16:34 UTC by AliakseiTsiukhai

2022-12-26 11:37 UTC, alexander-sidorov requested changes

2022-12-26 11:37 UTC, alexander-sidorov commented on hw/alexey_tyuhai/lesson10/lesson_test.py
> +    with open("data.json") as g:
Очень круто!

Но вот смотри, я беру твою ветку, качаю себе: никаких изменений нет.

Запускаю тесты, сохраняю результаты в свой файл.

Смотрю статус: свой файл вижу, а `data.json` - это что??

<img width="715" alt="image" src="https://user-images.githubusercontent.com/76160017/209544473-62dd26e2-69e0-4272-9867-5c79abc088cc.png">

Я-то его не закоммичу, и ты не закоммитил, но мы вмержим твой код в `main`, и этот файл будет создаваться у всех остальных, и кто-нибудь его закоммитит))

Предлагаю от него избавиться одним из двух способов:
1. `tempfile` [(документация)](https://docs.python.org/3/library/tempfile.html)
2. `tmpdir` [(документация)](https://docs.pytest.org/en/7.1.x/how-to/tmp_path.html)

2022-12-26 13:21 UTC, AliakseiTsiukhai commented on hw/alexey_tyuhai/lesson10/lesson_test.py
> +    with open("data.json") as g:
что-то усложнилось)))
![image](https://user-images.githubusercontent.com/118986917/209553343-df6ac248-6406-48c0-90d5-3ff7ccbe4ca7.png)

2022-12-27 12:14 UTC, AliakseiTsiukhai commented on hw/alexey_tyuhai/lesson10/lesson_test.py
> +    with open("data.json") as g:
Александр, помогите пожалуйста разобраться
![image](https://user-images.githubusercontent.com/118986917/209664915-f6e84bdf-8d49-4828-b52d-d24dfd3f8900.png)

здесь создаю временный файл(там лежит именно то что мне нужно) и пока не удаляю его, но как мне после его создания "взять" его название в папке(которое генерится рандомно) и запихнуть в тестовую функцию?

2022-12-27 12:41 UTC, alexander-sidorov commented on hw/alexey_tyuhai/lesson10/lesson_test.py
> +    with open("data.json") as g:
начать стоит с того, чтобы переименовать параметр, отвечающий за путь к файлу для сохранения, из `func_json` в `destination: str | Path`. `Path` импортируется из `pathlib`.

затем, в функции сохранения написать так:

```python
json_file = Path(destination)
with json_file.open("w") as stream:
    json.dump(stream, {"name": self.name})
```

затем, в тесте, вот именно в тесте! - создать [временный файл(папку)](https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory) и:

```python
with tempfile.TemporaryDirectory() as _tmpdir:
    tmpdir = Path(_tmpdir)
    assert tmpdir.is_dir()

    json_file = tmpdir / "kekeke.json"
    assert not json_file.is_file()

    user.save_json(json_file)
    assert json_file.is_file()

    with json_file.open("r") as stream:
        jsonobj = json.load(stream)
        assert jsonobj == {"name": "User Userovich"}
```


то есть, резюмируюя:
1. функция в классе сохраняет жсон в тот файл, который ей дадут
2. тест создаёт временную папку/файл, даёт её попользоваться подопытной функции, посте тестов всё  удаляет (за это отвечает `with ...`)

2022-12-27 13:44 UTC, AliakseiTsiukhai commented on hw/alexey_tyuhai/lesson10/lesson_test.py
> +    with open("data.json") as g:
что-то не идет
![image](https://user-images.githubusercontent.com/118986917/209675236-0e3dad5e-e83f-40a7-b926-4e07a7098b31.png)
и тут Pycharm ругается
![image](https://user-images.githubusercontent.com/118986917/209675342-28fa6e83-a949-4b40-ae86-fff3aba62f91.png)

2022-12-27 13:47 UTC, AliakseiTsiukhai commented on hw/alexey_tyuhai/lesson10/lesson_test.py
> +    with open("data.json") as g:
вот вся тестовая функция
![image](https://user-images.githubusercontent.com/118986917/209675767-ed8db176-bd5d-41ed-ae50-8454a0d067f7.png)

2022-12-27 15:15 UTC, alexander-sidorov commented on hw/alexey_tyuhai/lesson10/lesson_test.py
> +    with open("data.json") as g:
так всё прекрасно? и у меня тесты проходят, и у github.

2022-12-27 15:16 UTC, alexander-sidorov requested changes

2022-12-27 15:16 UTC, alexander-sidorov commented on hw/alexey_tyuhai/lesson10/lesson.py
> +        with open("data.json", "w") as g:
так это надо переписать же

2022-12-27 15:16 UTC, alexander-sidorov commented on hw/alexey_tyuhai/lesson10/lesson_test.py
> +    with open("data.json") as g:
я понял)) запушиь плз все изменения

2022-12-27 20:00 UTC, alexander-sidorov approved these changes

2022-12-27 20:02 UTC, merged