Vladislav Yurenya 12
alexander-sidorov/m-pt1-58-22 pull request #97
Opened 2022-12-23 16:12 UTC by varfalomey777

2022-12-27 20:33 UTC, alexander-sidorov requested changes

2022-12-27 20:33 UTC, alexander-sidorov commented on hw/vladislav_yurenya/lesson12/lesson.py
> +        new = urlparse(self.url)
ТЗ

2022-12-27 20:33 UTC, alexander-sidorov commented on hw/vladislav_yurenya/lesson12/lesson.py
> +        rew = headers.split(" ")
а зачем в 52 делать джоин, чтобы потом сразу же сделать сплит?

2022-12-27 20:33 UTC, alexander-sidorov commented on hw/vladislav_yurenya/lesson12/lesson.py
> +        self.headers["Accept"] = rew[1]
ок, вижу код для 5 заголовков идущих по алфавиту

а теперь, пожалуйста, сделай код для
- всех [185 основных](https://www.iana.org/assignments/message-headers/message-headers.xml#perm-headers%7CMessage)
- идущих в произвольном порядке, а не по алфавиту
- и вообще для любых кастомных (начинаются на `X-`)

2022-12-27 20:33 UTC, alexander-sidorov commented on hw/vladislav_yurenya/lesson12/lesson.py
> +            "Content-Length": int(new[1]),
та же ситуация, что и с заголовками ХТТП запроса

2022-12-27 20:33 UTC, alexander-sidorov commented on hw/vladislav_yurenya/lesson12/lesson.py
> +        if self.headers["Content-Length"] == len(self.body):  # noqa: SIM103
flake8 тут прав. попробуй переформулировать так, как он просит ([SIM103](https://github.com/MartinThoma/flake8-simplify/issues/3))

2022-12-28 08:59 UTC, varfalomey777 commented on hw/vladislav_yurenya/lesson12/lesson.py
> +        new = urlparse(self.url)
Тут я бессилен, пытался без urlparse, ничего не вышло(

2022-12-28 09:04 UTC, alexander-sidorov commented on hw/vladislav_yurenya/lesson12/lesson.py
> +        new = urlparse(self.url)
это ничего страшного)
можно еще погуглить про регулярные выражения)

2022-12-28 09:11 UTC, varfalomey777 commented on hw/vladislav_yurenya/lesson12/lesson.py
> +        new = urlparse(self.url)
пробовал через регулярки, тоже не вышло, после этого психанул и начал импортить urlparse)

2022-12-30 15:28 UTC, varfalomey777 commented on hw/vladislav_yurenya/lesson12/lesson.py
> +        new = urlparse(self.url)
не вышло(

2023-01-04 13:04 UTC, alexander-sidorov commented on hw/vladislav_yurenya/lesson12/lesson.py
> +        for i in range(len(for_headers)):
тут попрошу использовать `enumerate`

2023-01-04 13:04 UTC, alexander-sidorov commented on hw/vladislav_yurenya/lesson12/lesson.py
> +        for i in range(len(for_headers)):
хотя, даже не `enumerate` - тут пойдет `for header in for_headers`

2023-01-04 13:04 UTC, alexander-sidorov commented on hw/vladislav_yurenya/lesson12/lesson.py
> +        self.headers["Content-Length"] = int(self.headers["Content-Length"])
что будет, если такой заголовок будет отсутствовать в ответе?

2023-01-05 08:13 UTC, varfalomey777 commented on hw/vladislav_yurenya/lesson12/lesson.py
> +        self.body = url[body:]
Проверил через isinstance self.body - строка

2023-01-05 08:30 UTC, varfalomey777 commented on hw/vladislav_yurenya/lesson12/lesson.py
> +        self.url = re.split('" "|\n', self.url)
Чтобы всю полученную строку преобразовать в список -> вычленять из списка self.method, self.path,    self.http_version

2023-01-05 08:47 UTC, varfalomey777 commented on hw/vladislav_yurenya/lesson12/lesson.py
> +        for_headers = self.url.split("\n    ")
Чтобы убрать пробелы 
join+split - не помогло
replace - тоже не помог

2023-01-05 10:04 UTC, varfalomey777 commented on hw/vladislav_yurenya/lesson12/lesson.py
> +    def is_valid(self) -> Any:
если ставлю bool то: error: Returning Any from function
declared to return "bool" [no-any-return]
return self.headers["Content-Length"] == len(self.body)
Но весь прикол в том , то оно возвращает bool, искал как это пофиксить наткнулся что boolзаменить на Any

2023-01-05 13:35 UTC, varfalomey777 commented on hw/vladislav_yurenya/lesson12/lesson.py
> +        for_headers = self.url.split("\n    ")
исправил

2023-01-05 13:35 UTC, varfalomey777 commented on hw/vladislav_yurenya/lesson12/lesson.py
> +        for i in range(len(for_headers)):
исправил

2023-01-05 13:35 UTC, varfalomey777 commented on hw/vladislav_yurenya/lesson12/lesson.py
> +        self.headers["Content-Length"] = int(self.headers["Content-Length"])
исправил

2023-01-05 13:35 UTC, varfalomey777 commented on hw/vladislav_yurenya/lesson12/lesson.py
> +        self.url = url
исправил

2023-01-07 16:03 UTC, alexander-sidorov requested changes

2023-01-07 16:03 UTC, alexander-sidorov commented on hw/vladislav_yurenya/lesson12/lesson.py
> +    def is_valid(self) -> Any:
но смотри, ведь функция `is_valid` даже по названию говорит "да/нет", True/False, то есть она должна возвращать `bool`, то есть это должно быть записано в сигнатуре;

написать `Any` вместо `bool` равносильно вообще отключить проверку.

я веду к тому, что - да, возвращается в примерах в тестах bool, но по коду, по реализации, такой вывод сделать не получается. Отсюда следует, что нужно пофиксить код, а не сигнатуру: найти такое решение, чтобы по нему очевидно было, что вернётся bool данные.

2023-01-08 08:49 UTC, varfalomey777 commented on hw/vladislav_yurenya/lesson12/lesson.py
> +    def is_valid(self) -> Any:
Я понял)

2023-01-09 23:41 UTC, alexander-sidorov requested changes

2023-01-09 23:41 UTC, alexander-sidorov commented on hw/vladislav_yurenya/lesson12/lesson.py
> +        self.c = {
зачем создавать этот словарь, если можно сразу атрибуты результата `urlparse` пересохранить в атрибуты своего объекта?

2023-01-09 23:41 UTC, alexander-sidorov commented on hw/vladislav_yurenya/lesson12/lesson.py
> +        self.path = self.c["path"]
```python
self.path = new.path or None
```
и так со всем остальным

2023-01-09 23:41 UTC, alexander-sidorov commented on hw/vladislav_yurenya/lesson12/lesson.py
> +        for i in range(len(qef) - 2):
если `i` нужно только для получения элемента списка, то надо итерировать по самим элементам, а не по их позициям

2023-01-09 23:41 UTC, alexander-sidorov commented on hw/vladislav_yurenya/lesson12/lesson.py
> +        for i in range(len(qef) - 2):
вижу, что тут пропускаются крайние 2 элемента, так это надо решать выше, либо в строке 49, либо концептуально на уровне всего алгоритма

2023-01-10 17:35 UTC, varfalomey777 commented on hw/vladislav_yurenya/lesson12/lesson.py
> +        for i in range(len(qef) - 2):
исправил

2023-01-10 17:36 UTC, varfalomey777 commented on hw/vladislav_yurenya/lesson12/lesson.py
> +        self.path = self.c["path"]
пофиксил

2023-01-10 22:00 UTC, alexander-sidorov requested changes

2023-01-10 22:00 UTC, alexander-sidorov commented on hw/vladislav_yurenya/lesson12/lesson.py
> +        deleted = self.body.find("\n   ")
здесь - аналогично. Зачем в body мы ищем именно эту комбинацию - переход и три пробела?

2023-01-11 10:14 UTC, varfalomey777 commented on hw/vladislav_yurenya/lesson12/lesson.py
> +        left = self.url.find("{")
Я уже тоже с трудом свои мысли ,которые вложил в код понимаю))
Сейчас попробую исправить

2023-01-16 11:10 UTC, alexander-sidorov commented
к сожалению, не удалось правильно сделать логику HttpRequest и HttpResponse:

```python
from hw.vladislav_yurenya.lesson12.lesson import HttpRequest
from hw.vladislav_yurenya.lesson12.lesson import HttpResponse

body = """


x
y
z

1

2

"""

rq_message = f"""GET / HTTP/1.1
a: b
c: d

{body}"""

rs_message = f"""HTTP/1.1 200 OK
x: 1
y: 2

{body}"""


def case1() -> None:
    rq = HttpRequest(rq_message)

    assert rq.body == body


def case2() -> None:
    rs = HttpResponse(rs_message)

    assert rs.body == body


if __name__ == "__main__":
    case1()
    case2()

```

вот такой код падает с ошибкой:

```python
Traceback (most recent call last):
  File "m-pt1-58-22/hw/vladislav_yurenya/lesson12/corner_cases.py", line 43, in <module>
    case1()
  File "m-pt1-58-22/hw/vladislav_yurenya/lesson12/corner_cases.py", line 31, in case1
    rq = HttpRequest(rq_message)
  File "m-pt1-58-22/hw/vladislav_yurenya/lesson12/lesson.py", line 37, in __init__
    self.headers[count[0]] = count[1]
IndexError: list index out of range
```

с учетом того, что
1. используется urlparse
2. неправильно работает HttpRequest
3. неправильно работает HttpResponse
4. я давал подсказки, на что обратить внимание и исправить,

больше 6 за работу поставить не могу

2023-01-16 11:13 UTC, merged