Eugene Lubimov lesson12
alexander-sidorov/m-pt1-58-22 pull request #98
Opened 2022-12-23 16:13 UTC by 05TELO

2022-12-24 16:15 UTC, alexander-sidorov requested changes

2022-12-24 16:15 UTC, alexander-sidorov commented on hw/eugene_lubimov/lesson12/lesson12.py
> +        return self.req[0].split()[0]
предложу такие моменты оптимизировать: вызывать `split()` один раз, а компоненты посохранять и отдавать готовые в момент вызова метода

2022-12-24 16:15 UTC, alexander-sidorov commented on hw/eugene_lubimov/lesson12/lesson12.py
> +        for head in self.req[1:-3]:
надо найти индекс пустой строки в списке, это и будет номер, на котором заканчиваются строки с заголовками

2022-12-24 16:15 UTC, alexander-sidorov commented on hw/eugene_lubimov/lesson12/lesson12.py
> +            head1: list = head.split(": ")
в целях избавления от индексаций предложу делать вот так:

```python
header, value = head.split(": ")
```

2022-12-26 11:18 UTC, alexander-sidorov requested changes

2022-12-26 11:18 UTC, alexander-sidorov commented on hw/eugene_lubimov/lesson12/lesson12.py
> +        self.__dict__.update(my_dict)
Магические атрибуты напрямую трогать нельзя.

Если надо для объекта создать атрибут, то следует пользоваться оператором `.`: `self.scheme = ...`

2022-12-26 11:18 UTC, alexander-sidorov commented on hw/eugene_lubimov/lesson12/lesson12.py
> +            self.host: str = other
Ошибка

```
hw/eugene_lubimov/lesson12/lesson12.py:40: error: Attribute "host" already
defined on line 37  [no-redef]
                self.host: str = other
                ^
```

и возникает по причине того, что атрибуты создаются в обход.

Mypy не видит (и я сразу не увидел и никакой программист не увидит), что атрибуты устанавливаются в `self.__dict__.fromkeys()`.

Так бы этой ошибки не было.

2022-12-26 11:18 UTC, alexander-sidorov commented on hw/eugene_lubimov/lesson12/lesson12.py
> +        return self._HttpRequest__http_version.title()
Это тоже хак в обход нормального использования кода.

К тому же неверный: HTTP reason != HTTP version, всегда.

2022-12-26 11:18 UTC, alexander-sidorov commented on hw/eugene_lubimov/lesson12/lesson12.py
> +        return int(self.path)
не думаю, что `a,b,c = d.split(" ")` будет менее эффективно, и вообще хоть чем-то хуже, чем наследование + неработающие хаки + нечитаемые хаки типа "статус - это путь" :D

2022-12-26 11:18 UTC, alexander-sidorov commented on hw/eugene_lubimov/lesson12/lesson12.py
> +        return self.headers["Content-Length"] == len(self.body)
`self.body`, согласно типам, и согласно логике, может быть как `str`, так и `None`.

`len(str())` вычислить можно.

`len(None)` — нельзя.

mypy указывает именно на это.

2022-12-26 11:18 UTC, alexander-sidorov commented on hw/eugene_lubimov/lesson12/lesson12.py
> +            return self.__json
`Missing return statement ` означает, что в случае false clause инструкции `if` в функции произойдёт _неявный_ выход, а это как раз то, что не нравится никому)

2022-12-26 11:18 UTC, alexander-sidorov commented on hw/eugene_lubimov/lesson12/lesson12.py
> +                self.__json = json.loads(self.body)
`self.body` может быть `None`, а `json.loads` работает только со строками. Напомню, его функция — перевести строку с буквами в JSON объект. `None` — это не строка с буквами.

2022-12-26 11:18 UTC, alexander-sidorov commented on hw/eugene_lubimov/lesson12/lesson12.py
> +                self.__json = json.loads(self.body)
Здесь сразу 2 проблемы.

**Первая.** Я не нашёл `self.__json` в конструкторе класса, а значит, этот атрибут может быть чем угодно. Но функция обещает вернуть `str`.

То есть несовпадение того, что фактически возвращается, с тем, что обещается.

**Вторая**. Функция `to_json()` вообще не может обещать какой-то конкретный тип! Что обещает возвращать `json.loads()`?

Ближайшее, что можно обещать — это `None | bool | int | float | str | list | dict`. И то, "ближайшее", то есть и не факт что именно это.

2022-12-26 11:18 UTC, alexander-sidorov commented on hw/eugene_lubimov/lesson12/test_lesson12.py
> +    req = """HEAD /docs/python_3/library/urllib.parse.html HTTP/1.1
в строке 67 написано, что `req` — это `HttpRequest`. А теперь почему-то он - `req` - становится строкой!

2022-12-26 15:43 UTC, 05TELO commented on hw/eugene_lubimov/lesson12/lesson12.py
> +        return int(self.path)
мне показало сь логика инита почти такая же и я решил что наследование будет очень кстати))в процессе понял что не очень ,но остановиться уже не мог)

2022-12-26 18:09 UTC, alexander-sidorov commented on hw/eugene_lubimov/lesson12/lesson12.py
> +        return int(self.path)
правильная мысль! наследование тут к месту. но текст читают человеки, и названия сбивают с толку, а хаки в обход принятых практик вообще опасны

2022-12-26 18:15 UTC, alexander-sidorov requested changes

2022-12-26 18:15 UTC, alexander-sidorov commented on hw/eugene_lubimov/lesson12/lesson12.py
> +        return
выглядит некрасиво?
вот решение: 

вместо

```python
if "так":
    ...
    # основной поток
    ...
```

закрывать неудачи сразу:

```python
if "не так":
    return

...
# основной поток
...
```

2023-01-04 12:54 UTC, alexander-sidorov requested changes

2023-01-07 15:58 UTC, alexander-sidorov requested changes

2023-01-07 15:58 UTC, alexander-sidorov commented on hw/eugene_lubimov/lesson12/lesson12.py
> +    def is_valid(self) -> Any:
я не согласен: `is_valid` даже по названию говорит "да/нет", True/False, то есть возвращает `bool` а не `Any`

2023-01-09 23:43 UTC, alexander-sidorov approved these changes

2023-01-09 23:45 UTC, merged